name: dotnist-grpc

services:
  dotnist-grpc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_SOURCE_PATH: rds/RDS_2025.09.1_modern_minimal_patched_flattened.db
    ports:
      - "3381:3381"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=3381
