name: Build and Push gRPC Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for GitVersion to work properly
      
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'
      
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.11
      with:
        configFilePath: GitVersion.yml
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push gRPC image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          VERSION=${{ steps.gitversion.outputs.semVer }}
          ASSEMBLY_VERSION=${{ steps.gitversion.outputs.assemblySemVer }}
          FILE_VERSION=${{ steps.gitversion.outputs.assemblySemFileVer }}
          INFORMATIONAL_VERSION=${{ steps.gitversion.outputs.informationalVersion }}
        tags: |
          ghcr.io/elemdiscovery/dotnist-grpc:latest
          ghcr.io/elemdiscovery/dotnist-grpc:${{ steps.gitversion.outputs.semVer }}
          ghcr.io/elemdiscovery/dotnist-grpc:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max 

    - name: Verify Images
      run: docker manifest inspect ghcr.io/elemdiscovery/dotnist-grpc:latest 